services:
  postgres:
    image: postgres
    container_name: fake-news
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    working_dir: /app
    ports:
      - "5432:${PGPORT}"
    volumes:
      - .:/app
      - ./src/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    restart: always
