name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Commit and push changes to production branch
        run: |
          git push origin --delete production || true
          git branch --delete production || true
          git checkout --orphan production
          git rm -rf . && git checkout HEAD --dist/
          git checkout main -- package.json endpoints.json package-lock.json
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -n -m "Build and compile production"
          git push origin production
